//editor //discontinue some of these
export const PARENTHESES_ACTION = 'PARENTHESES_ACTION';
export const OPERATOR_ACTION = 'OPERATOR_ACTION';
export const DIGIT_ACTION = 'DIGIT_ACTION';

//create
export const CREATE_BLOCK_ACTION = 'CREATE_BLOCK_ACTION';
export const CREATE_NUMBER_ACTION = 'CREATE_NUMBER_ACTION';
export const TARGET_BLOCK_ACTION = 'TARGET_BLOCK_ACTION';
export const ENTER_BLOCK_ACTION = 'ENTER_ACTION';
export const ERASE_BLOCK_ACTION = 'ERASE_ACTION';
export const REMOVE_BLOCK_ACTION = 'REMOVE_BLOCK_ACTION';

//expression
export const NUMBER_ACTION = 'NUMBER_ACTION';
export const DIVISION_ACTION = 'DIVISION_ACTION';
export const MULTIPLICATION_ACTION = 'MULTIPLICATION_ACTION';
export const ADDITION_ACTION = 'ADDITION_ACTION';
export const EXPAND_ACTION = 'EXPAND_ACTION';
export const COMPRESS_ACTION = 'COMPRESS_ACTION';

//UI (need id)
export const TOGGLE_FACTORS = 'TOGGLE_FACTORS';
